import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import LeftNav from "@/components/LeftNav/LeftNav";
import TopHeader from "@/components/TopHeader";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["500", "600", "100", "200", "300", "400", "700", "800", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="mainLayout flex min-h-[100dvh] justify-between relative overflow-x-hidden text-slate-400 text-xs">
          <LeftNav />

          <section className="grow py-8 md:pb-16 pt-0 overflow-y-auto max-h-[100dvh]">
            <TopHeader />
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
