import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import LeftNav from "@/components/LeftNav/LeftNav";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["500", "600", "100", "200", "300", "400", "700", "800", "900"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="mainLayout flex min-h-screen justify-between relative text-slate-400">
          <LeftNav />

          {children}
        </main>
      </body>
    </html>
  );
}
